export type VehicleCategory = "compact" | "sedan" | "suv" | "7s" | "bikes";

export interface MarketingCar {
  slug: string;
  inventoryId: string;
  category: VehicleCategory;
  brand: string;
  model: string;
  year: number;
  image: string;
  fromPrice: number;
  deposit: number;
  seats: string;
  transmission: string;
  engine: string;
  fuel: string;
  summary: string;
  bestFor: string;
}

export const vehicleCategories: Array<{
  id: VehicleCategory;
  name: string;
  shortName: string;
  description: string;
}> = [
  {
    id: "compact",
    name: "Компактные автомобили",
    shortName: "Компакт",
    description: "Манёвренные машины для пляжей, кафе и ежедневных поездок.",
  },
  {
    id: "sedan",
    name: "Седаны",
    shortName: "Седаны",
    description: "Комфорт для дальних маршрутов и поездок по всему острову.",
  },
  {
    id: "suv",
    name: "Кроссоверы и SUV",
    shortName: "SUV",
    description: "Больше пространства, высокая посадка и уверенность в дороге.",
  },
  {
    id: "7s",
    name: "Автомобили на 7+ мест",
    shortName: "7+ мест",
    description: "Просторные варианты для семьи, компании и большого багажа.",
  },
  {
    id: "bikes",
    name: "Байки и максискутеры",
    shortName: "Байки",
    description: "Свобода передвижения по Пхукету без пробок и поиска парковки.",
  },
];

export const marketingCars: MarketingCar[] = [
  {
    slug: "toyota-yaris",
    inventoryId: "toyota_yaris_2024_gray",
    category: "compact",
    brand: "Toyota",
    model: "Yaris",
    year: 2024,
    image: "/images_web/compact/ar_yaris_premium_gray_2024/1.jpg",
    fromPrice: 425,
    deposit: 5000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "1.2 л",
    fuel: "Бензин",
    summary: "Экономичный городской автомобиль с понятными габаритами и лёгкой парковкой.",
    bestFor: "Пар, небольших семей и ежедневных поездок по острову.",
  },
  {
    slug: "suzuki-swift",
    inventoryId: "namo_suzuki_swift_2020",
    category: "compact",
    brand: "Suzuki",
    model: "Swift",
    year: 2020,
    image: "/images_web/compact/namo_suzuki_swift_2020/1.jpg",
    fromPrice: 425,
    deposit: 5000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "1.3 л",
    fuel: "Бензин",
    summary: "Компактный хэтчбек с живой управляемостью и небольшим расходом топлива.",
    bestFor: "Городских маршрутов, пляжей и узких улиц Пхукета.",
  },
  {
    slug: "honda-jazz",
    inventoryId: "Nm_jazz_white_2019",
    category: "compact",
    brand: "Honda",
    model: "Jazz",
    year: 2019,
    image: "/images_web/compact/Nm_jazz_white_2019/7.jpg",
    fromPrice: 475,
    deposit: 5000,
    seats: "5 мест",
    transmission: "CVT",
    engine: "1.5 л",
    fuel: "Бензин",
    summary: "Компактный снаружи и удивительно просторный внутри хэтчбек.",
    bestFor: "Путешествий вдвоём, семей с ребёнком и багажа.",
  },
  {
    slug: "toyota-vios",
    inventoryId: "namo_vios_white_2022",
    category: "compact",
    brand: "Toyota",
    model: "Vios",
    year: 2022,
    image: "/images_web/compact/namo_vios_white_2022/1.jpg",
    fromPrice: 425,
    deposit: 5000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "1.5 л",
    fuel: "Бензин",
    summary: "Практичный автомобиль с вместительным багажником и спокойным характером.",
    bestFor: "Повседневной аренды и поездок между районами острова.",
  },
  {
    slug: "toyota-ativ",
    inventoryId: "toyota_ativ_2024_gray",
    category: "sedan",
    brand: "Toyota",
    model: "Ativ",
    year: 2024,
    image: "/images_web/sedan/ar_ativ_dark_gray_2024/1.jpg",
    fromPrice: 453,
    deposit: 5000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "1.2 л",
    fuel: "Бензин",
    summary: "Современный седан с мягкой подвеской, камерой и просторным салоном.",
    bestFor: "Комфортных поездок по Пхукету и трансферов с багажом.",
  },
  {
    slug: "honda-civic",
    inventoryId: "honda_civic_2024_black",
    category: "sedan",
    brand: "Honda",
    model: "Civic RS",
    year: 2024,
    image: "/images_web/sedan/ar_civic_rs_black_2024/1.jpg",
    fromPrice: 851,
    deposit: 5000,
    seats: "5 мест",
    transmission: "CVT",
    engine: "2.0 л",
    fuel: "Бензин",
    summary: "Динамичный седан с выразительным дизайном и уверенным запасом мощности.",
    bestFor: "Тех, кто ценит комфорт, стиль и удовольствие от дороги.",
  },
  {
    slug: "honda-city",
    inventoryId: "Ar_city_rs_black_2025",
    category: "sedan",
    brand: "Honda",
    model: "City RS",
    year: 2025,
    image: "/images_web/sedan/Ar_city_rs_black_2025/2.jpg",
    fromPrice: 425,
    deposit: 5000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "1.6 л",
    fuel: "Бензин",
    summary: "Свежий городской седан с удобным салоном и экономичным двигателем.",
    bestFor: "Длительной аренды и активных поездок каждый день.",
  },
  {
    slug: "toyota-camry",
    inventoryId: "toyota_camry_2020_black",
    category: "sedan",
    brand: "Toyota",
    model: "Camry",
    year: 2020,
    image: "/images_web/sedan/ar_camry_black_2020/1.jpg",
    fromPrice: 851,
    deposit: 5000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "2.5 л",
    fuel: "Бензин / гибрид",
    summary: "Большой комфортный седан для спокойных поездок на любые расстояния.",
    bestFor: "Деловых поездок, семей и повышенных требований к комфорту.",
  },
  {
    slug: "toyota-yaris-cross",
    inventoryId: "namo_yaris_cross_2025",
    category: "suv",
    brand: "Toyota",
    model: "Yaris Cross",
    year: 2025,
    image: "/images_web/suv/namo_yaris_cross_2025/2.jpg",
    fromPrice: 865,
    deposit: 10000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "1.5 л",
    fuel: "Бензин",
    summary: "Компактный кроссовер с высокой посадкой и современным оснащением.",
    bestFor: "Семей, активных маршрутов и поездок с пляжным снаряжением.",
  },
  {
    slug: "toyota-corolla-cross",
    inventoryId: "ar_corolla_cross_blue_2024",
    category: "suv",
    brand: "Toyota",
    model: "Corolla Cross",
    year: 2024,
    image: "/images_web/suv/ar_corolla_cross_blue_2024/1.jpg",
    fromPrice: 865,
    deposit: 10000,
    seats: "5 мест",
    transmission: "Вариатор",
    engine: "1.8 л",
    fuel: "Гибрид",
    summary: "Комфортный гибридный кроссовер с просторным салоном и экономичным ходом.",
    bestFor: "Дальних маршрутов по острову и семейного отдыха.",
  },
  {
    slug: "mazda-cx-30",
    inventoryId: "PW_mazda_cx30_gray_2023",
    category: "suv",
    brand: "Mazda",
    model: "CX-30",
    year: 2023,
    image: "/images_web/suv/PW_mazda_cx30_gray_2023/4.jpg",
    fromPrice: 865,
    deposit: 10000,
    seats: "5 мест",
    transmission: "Автомат",
    engine: "2.0 л",
    fuel: "Бензин",
    summary: "Стильный кроссовер с точной управляемостью и качественным интерьером.",
    bestFor: "Пар и небольших семей, которым важны дизайн и комфорт.",
  },
  {
    slug: "honda-hr-v",
    inventoryId: "ar_hrvrs_black_2024",
    category: "suv",
    brand: "Honda",
    model: "HR-V RS",
    year: 2024,
    image: "/images_web/suv/ar_hrvrs_black_2024/1.jpg",
    fromPrice: 945,
    deposit: 10000,
    seats: "5 мест",
    transmission: "CVT",
    engine: "1.5 л",
    fuel: "Гибрид",
    summary: "Современный гибридный SUV с высокой посадкой и гибким салоном.",
    bestFor: "Активного отдыха, багажа и комфортных поездок на весь день.",
  },
  {
    slug: "toyota-veloz",
    inventoryId: "toyota_veloz_2024_gray",
    category: "7s",
    brand: "Toyota",
    model: "Veloz",
    year: 2024,
    image: "/images_web/7s/namo_veloz_gray_2024/1.jpg",
    fromPrice: 851,
    deposit: 10000,
    seats: "7 мест",
    transmission: "CVT",
    engine: "1.5 л",
    fuel: "Бензин",
    summary: "Семиместный автомобиль с тремя рядами сидений и удобной посадкой.",
    bestFor: "Семей, компаний друзей и поездок с большим количеством вещей.",
  },
  {
    slug: "mitsubishi-xpander",
    inventoryId: "mitsubishi_xpander_2023_white",
    category: "7s",
    brand: "Mitsubishi",
    model: "Xpander",
    year: 2023,
    image: "/images_web/7s/namo_xpander_white_2023/1.jpg",
    fromPrice: 665,
    deposit: 10000,
    seats: "7 мест",
    transmission: "Автомат",
    engine: "1.5 л",
    fuel: "Бензин",
    summary: "Практичный семиместный минивэн с просторным салоном и мягким ходом.",
    bestFor: "Больших семей и путешествий по Пхукету одной машиной.",
  },
  {
    slug: "h1-12-seats",
    inventoryId: "Namo_h1_blackvagon_2023",
    category: "7s",
    brand: "H1",
    model: "12 Seats",
    year: 2023,
    image: "/images_web/7s/Namo_h1_blackvagon_2023/1.jpg",
    fromPrice: 1690,
    deposit: 10000,
    seats: "12 мест",
    transmission: "Автомат",
    engine: "2.5 л",
    fuel: "Дизель",
    summary: "Вместительный пассажирский автомобиль для большой компании и багажа.",
    bestFor: "Групп, трансферов и совместных поездок без второй машины.",
  },
  {
    slug: "toyota-alphard",
    inventoryId: "namo_alphard_white_2024",
    category: "7s",
    brand: "Toyota",
    model: "Alphard",
    year: 2024,
    image: "/images_web/7s/namo_alphard_white_2024/1.jpg",
    fromPrice: 5511,
    deposit: 30000,
    seats: "до 12 мест",
    transmission: "Автомат",
    engine: "2.5 л",
    fuel: "Гибрид",
    summary: "Премиальный минивэн с просторным салоном и высоким уровнем комфорта.",
    bestFor: "VIP-трансферов, больших семей и особых поездок.",
  },
  {
    slug: "honda-adv-350",
    inventoryId: "Fb_bike1_honda_adv350_black_2025",
    category: "bikes",
    brand: "Honda",
    model: "ADV 350",
    year: 2025,
    image: "/images_web/bikes/Fb_bike1_honda_adv350_black_2025/1.jpg",
    fromPrice: 395,
    deposit: 7000,
    seats: "2 места",
    transmission: "Автомат",
    engine: "350 см³",
    fuel: "Бензин",
    summary: "Универсальный максискутер с комфортной посадкой и запасом мощности.",
    bestFor: "Дальних маршрутов, поездок вдвоём и активного исследования острова.",
  },
  {
    slug: "yamaha-tmax",
    inventoryId: "Den_t-max2024",
    category: "bikes",
    brand: "Yamaha",
    model: "TMAX",
    year: 2024,
    image: "/images_web/bikes/Den_t-max2024/1.jpg",
    fromPrice: 969,
    deposit: 15000,
    seats: "2 места",
    transmission: "Автомат",
    engine: "Максискутер",
    fuel: "Бензин",
    summary: "Мощный премиальный максискутер для быстрых и комфортных маршрутов.",
    bestFor: "Опытных водителей и поездок на большие расстояния.",
  },
  {
    slug: "honda-forza-350",
    inventoryId: "Forza_350_2024_topbox",
    category: "bikes",
    brand: "Honda",
    model: "Forza 350",
    year: 2024,
    image: "/images_web/bikes/Forza_350_2024_topbox/1.jpg",
    fromPrice: 412,
    deposit: 10000,
    seats: "2 места",
    transmission: "Автомат",
    engine: "350 см³",
    fuel: "Бензин",
    summary: "Комфортный туристический максискутер с кофром для вещей.",
    bestFor: "Поездок вдвоём, пляжных маршрутов и путешествий на весь день.",
  },
  {
    slug: "yamaha-nmax-155",
    inventoryId: "Nmax_2024_blue_topbox",
    category: "bikes",
    brand: "Yamaha",
    model: "NMAX 155",
    year: 2024,
    image: "/images_web/bikes/Nmax_2024_blue_topbox/1.jpg",
    fromPrice: 204,
    deposit: 5000,
    seats: "2 места",
    transmission: "CVT",
    engine: "155 см³",
    fuel: "Бензин",
    summary: "Лёгкий и экономичный скутер с удобной посадкой и кофром.",
    bestFor: "Ежедневных поездок, пляжей и движения по загруженным районам.",
  },
];

export const getCarBySlug = (slug: string): MarketingCar | undefined =>
  marketingCars.find((car) => car.slug === slug);

export const getCarsByCategory = (category: VehicleCategory): MarketingCar[] =>
  marketingCars.filter((car) => car.category === category);

export const getCategoryById = (category: VehicleCategory) =>
  vehicleCategories.find((item) => item.id === category);
